### ISSUE TITLE
Crashes when case calling esp_mqtt_start(.........) 

### ISSUE THREAD

**Issue by wdouglas1999** [jessebraham/esp32-mqtt-client#3]
Good day,
Thank you for your efforts with the useful mqtt code.
I tested your code and it works perfectly in your example.
I am however trying to add it to my project and whenever I call this.
 case SYSTEM_EVENT_STA_GOT_IP:
            xEventGroupSetBits(wifi_event_group, CONNECTED_BIT);
            esp_mqtt_start(MQTT_HOST, MQTT_PORT, "esp-mqtt", MQTT_USER, MQTT_PASS);

The esp32 resets as follows:

[0;32mI (4166) event: sta ip: 192.168.1.102, mask: 255.255.255.0, gw: 192.168.1.1[0m
C:/msys32/home/wdoug/esp/esp-idf/components/freertos/queue.c:1441 (xQueueGenericReceive)- assert failed!
abort() was called at PC 0x40089035 on core 0

Backtrace: 0x4008a8dc:0x3ffbf2c0 0x4008aa03:0x3ffbf2e0 0x40089035:0x3ffbf300 0x40129021:0x3ffbf340 0x4010f03e:0x3ffbf370 0x4012a41d:0x3ffbf390 0x4012a461:0x3ffbf3b0

Rebooting...
The code compiles with no errors.
I am using IDF 3.0.

I would like to ask for your assistance on how to use your code in other projects.
thank you.

**Comment by jessebraham** [comment]
Hey, sorry about the delay, I was out of the country for a few weeks.

Unfortunately without any code there's not much I can do to help. If you're able to create a repo containing what you have so far I'd be more than happy to take a look at it.

A good start would be to just make sure you have the 256dpi/esp-mqtt component added to your project in the `components` directory properly, and that you have provided all required configuration items.

**Comment by wdouglas1999** [comment]
Hi! Thank you for the reply.
I have managed to get it working.
The issue was I was running some processes that were taking up to much processor time.
Thank you.
